; PlatformIO Project Configuration File

[env:cam]
framework = arduino
platform = espressif32
board = esp32-s3-devkitc-1
;board = esp32cam
board_build.psram = enabled
board_build.arduino.memory_type = qio_opi
monitor_speed = 115200
monitor_eol = CRLF
monitor_filters = esp32_exception_decoder
board_build.partitions = src/partitions.csv


;board_build.f_flash = 40000000
;board_build.f_cpu = 240000000L
build_flags = 
    -Wno-deprecated-declarations ; attention : toutes les deprecated sont masquees
    -Os              ; optimise pour la taille
    -ffunction-sections
    -fno-inline-small-functions
    -fdata-sections
    -Wl,-Map,firmware.map,--gc-sections
    -DCORE_DEBUG_LEVEL=3
    ;-DARDUHAL_LOG_LEVEL=1
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SUPPORT=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    ; Enable FreeRTOS run-time stats (may be overridden by FreeRTOSConfig.h if already defined)
    ;-DconfigGENERATE_RUN_TIME_STATS=1
    ;-DconfigUSE_TRACE_FACILITY=1
    ;-DINCLUDE_uxTaskGetSystemState=1
    ; Map the runtime counter macro to esp_timer_get_time (microseconds)
    ;-DportGET_RUN_TIME_COUNTER_VALUE=esp_timer_get_time
;lib_ldf_mode = chain+
;    -D CONFIG_BT_ENABLED=0
;    -D CONFIG_BLE_ENABLED=0
;    -DARDUINO_USB_MODE=1
;    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLPC_PROFILE
    ;-I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/sdk/esp32s3/include/fb_gfx/include"


lib_deps =
  bblanchon/ArduinoJson
  ESP32Async/AsyncTCP 
  ESP32Async/ESPAsyncWebServer
  https://github.com/gilmaimon/ArduinoWebsockets.git
  esp32-camera
  ;ClosedCube/ClosedCube HDC1080 @ ^1.1.1